<script lang="ts">
	import { Scale, Lock, AlertCircle } from 'lucide-svelte';
</script>

<svelte:head>
	<title>Terms of Service – SchoolCBT</title>
	<meta
		name="description"
		content="SchoolCBT terms of service — your rights and responsibilities as a student, tutor or school partner."
	/>
</svelte:head>

<div class="bg-background min-h-[calc(100vh-64px)] px-4 py-16">
	<div class="mx-auto max-w-3xl">
		<div class="mb-10 text-center">
			<div
				class="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-[hsl(var(--primary)/0.1)]"
			>
				<Scale class="h-7 w-7 text-[hsl(var(--primary))]" />
			</div>
			<div class="section-badge mb-4">Legal</div>
			<h1 class="text-foreground mb-2 text-3xl font-black">Terms of Service</h1>
			<p class="text-muted-foreground text-sm">Last updated: April 2025 · Effective immediately</p>
		</div>

		<div class="glass-panel prose prose-sm max-w-none space-y-8 p-8">
			{#each [{ title: '1. Acceptance of Terms', body: 'By accessing or using SchoolCBT, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform. These terms apply to all users including students, tutors, and school administrators.' }, { title: '2. Platform Description', body: 'SchoolCBT is a Results-as-a-Service (RaaS) platform that provides AI-generated Computer-Based Test (CBT) practice sessions, tutor matching, and academic performance analytics for Nigerian secondary and tertiary students preparing for JAMB, WAEC, NECO, NABTEB, and Post-UTME examinations.' }, { title: '3. Account Registration', body: 'You must provide accurate, complete, and current information during registration. You are responsible for maintaining the security of your account credentials. Students under 13 must have parental or guardian consent to use the platform.' }, { title: '4. Subscription & Payments', body: 'Access to SchoolCBT features requires a paid subscription. The Student Single Exam plan is ₦10,000 per exam type. The Student + Tutor plan is ₦35,000. All fees are non-refundable after the first 48 hours of access unless a technical failure on our part prevented access entirely. Payments are processed securely via Paystack or Stripe.' }, { title: '5. Acceptable Use', body: 'You may not use SchoolCBT to share login credentials, scrape or reproduce AI-generated content commercially, misrepresent identity during tutor sessions, or engage in any form of academic dishonesty. Violation of these terms will result in immediate account suspension without refund.' }, { title: '6. Tutor Obligations', body: 'Tutors registered on SchoolCBT must maintain professional conduct, attend all scheduled sessions, and are subject to student performance-based evaluations. Tutors receive payment only after sessions are confirmed complete. SchoolCBT reserves the right to remove any tutor who fails to meet platform standards.' }, { title: '7. Intellectual Property', body: "All content generated by SchoolCBT's AI system — including question banks, explanations, study plans, and report cards — is the intellectual property of EwinProject. You may use this content only for personal study purposes. Reproduction or redistribution for commercial purposes is strictly prohibited." }, { title: '8. Limitation of Liability', body: 'SchoolCBT does not guarantee exam success. AI-generated content, while verified for accuracy, may contain errors. EwinProject is not liable for any damages arising from reliance on platform content. In all circumstances, our maximum liability is limited to the subscription fee paid in the 30 days prior to the claim.' }, { title: '9. Privacy', body: 'Our Privacy Policy governs the collection and use of your personal data. By using SchoolCBT, you consent to the processing of your data as described in the Privacy Policy.' }, { title: '10. Changes to Terms', body: 'We reserve the right to update these Terms of Service at any time. We will notify registered users of significant changes via email. Continued use of the platform after notification constitutes acceptance of the updated terms.' }, { title: '11. Governing Law', body: 'These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the competent courts of Lagos State, Nigeria.' }] as section}
				<div>
					<h2 class="text-foreground mb-3 text-base font-black">{section.title}</h2>
					<p class="text-muted-foreground text-sm leading-relaxed">{section.body}</p>
				</div>
			{/each}

			<div class="border-border border-t pt-6">
				<p class="text-muted-foreground text-xs">
					For questions about these terms, contact us at
					<a
						href="mailto:legal@schoolcbt.dev"
						class="font-semibold text-[hsl(var(--primary))] hover:underline">legal@schoolcbt.dev</a
					>
				</p>
			</div>
		</div>
	</div>
</div>
